version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
     - "2181:2181"

  kafka:
    build: "https://github.com/wurstmeister/kafka-docker.git#0.9.0.1"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tlog:1:1"
    depends_on:
      - zookeeper

#  eclair:
#    image: eclairjs/minimal-gateway
#    ports:
#      - "8888:8888"
#    volumes:
#      - ./data:/data
#    depends_on:
#      - kafka

  pump:
    image: java:8
    volumes:
      - ./docker:/pump
      - ./data/streaming:/streaming
    command: "/pump/DTPump/DTPump-0.1.3/bin/dt-pump --repeat --broker-list=${KAFKA_HOST}:9092 --data-dir=/streaming --topic=tlog --data-rate=2 --throttle=500 --verbose"
    depends_on:
      - kafka

