version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "airline:1:1"
    depends_on:
      - zookeeper

  eclair:
    image: eclairjs/minimal-gateway
    ports:
      - "8888:8888"
    volumes:
      - ./data/2008bd.json:/staticdata
    depends_on:
      - kafka

  pump:
    image: java:8
    volumes:
      - ../kafka-pump:/pump
      - ./data/streaming:/data
    command: "/pump/bin/dt-pump --broker-list=kafka:9092 --data-dir=/data --topic=airline --data-rate=100 --throttle=1000 --verbose"
    depends_on:
      - kafka
